version: 0.1

phases:
  build:
    commands:
      - yarn install
      - yarn webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - Benjamin_Geyer_Resume.pdf
    - styles/main.css
    - images/*
    - dist/*